#cloud-config
package_update: true
package_upgrade: true

packages:
  - git
  - python3
  - python3-pip
  - python3-venv

write_files:
  - path: /tmp/local.conf
    content: |
      [[local|localrc]]
      ADMIN_PASSWORD=nomoresecret
      DATABASE_PASSWORD=stackdb
      RABBIT_PASSWORD=stackqueue
      SERVICE_PASSWORD=$ADMIN_PASSWORD
      enable_plugin eduvmstore-ui https://github.com/samuelhilpert/eduvmstore-ui main
    permissions: '0644'
    owner: root:root

  - path: /tmp/init.sh
    content: |
      #!/bin/bash
      HOME_DIR="/home/ubuntu"
      DEVSTACK_DIR="$HOME_DIR/devstack"

      cp /tmp/local.conf "$HOME_DIR/local.conf"
      chown ubuntu:ubuntu "$HOME_DIR/local.conf"

      sudo -u ubuntu git clone https://opendev.org/openstack/devstack "$DEVSTACK_DIR"
      cp "$HOME_DIR/local.conf" "$DEVSTACK_DIR/local.conf"
      chown -R ubuntu:ubuntu "$DEVSTACK_DIR"
      pip3 install reportlab
    permissions: '0755'
    owner: root:root

