line-length = 110
exclude = [
    "migrations/",
    "myplugin/content/admin/tests/",
    "myplugin/content/eduvmstore/tests/",
]
# Todo: richtig, dass die tests excludet sind?


# Enable specific rule categories
# E: Pyflakes (syntax errors, undefined names, etc.)
# F: Flake8 (standard Python errors)
# N: PEP 8 naming conventions (e.g., CamelCase for classes, snake_case for functions)
# I: Import check (unused imports, import order)
[lint]
ignore = ["F811"]
select = ["E", "F", "N", "I"]


