line-length = 110
exclude = ["migrations", "tests/"]

# Aktivieren spezifischer Regelkategorien
# E: Pyflakes (Syntax-Fehler, undefinierte Namen, etc.)
# F: Flake8 (Standard-Python-Fehler)
# N: PEP 8 Namenskonventionen (z.B. CamelCase für Klassen, snake_case für Funktionen)
# I: Import-Check (unbenutzte Importe, Import-Reihenfolge)
select = ["E", "F", "N", "I"]


