name: Ruff Linting

on:
  # Löst Linting bei jedem Pull Request und Push auf den "main"- und "dev"-Branch aus
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken
      - name: Checkout code
        uses: actions/checkout@v4

      # Ruff Linting ausführen
      - name: Run Ruff Check
        uses: astral-sh/ruff-action@v3
        with:
          args: check --config ruff.toml --fix

      # Ruff Formatierung ausführen
      - name: Run Ruff Format
        uses: astral-sh/ruff-action@v3
        with:
          args: format --config ruff.toml
