name: Ruff Linting

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Ruff Linting
      - name: Run Ruff Check
        uses: astral-sh/ruff-action@v3
        with:
          args: check --config ruff.toml --fix

      # Ruff Formatierung
      - name: Run Ruff Format
        uses: astral-sh/ruff-action@v3
        with:
          args: format --config ruff.toml
