name: Run Django Tests

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install django pytest requests

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest myplugin/content/eduvmstore/tests/
          pytest myplugin/content/admin/tests/
