name: Vulture Analysis

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev

jobs:
  vulture:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Vulture
        run: |
          python -m pip install --upgrade pip
          pip install vulture

      - name: Run Vulture
        run: |
          vulture . --ignore-names "SECRET_KEY,DEBUG,ALLOWED_HOSTS,INSTALLED_APPS,MIDDLEWARE,ROOT_URLCONF,TEMPLATES,WSGI_APPLICATION,DATABASES,AUTH_PASSWORD_VALIDATORS,LANGUAGE_CODE,TIME_ZONE,USE_I18N,USE_TZ,STATIC_URL,DEFAULT_AUTO_FIELD,application,urlpatterns,name,slug,template_name,PANEL,PANEL_DASHBOARD,ADD_PANEL,ADD_INSTALLED_APPS,ADD_ANGULAR_MODULES,AUTO_DISCOVER_STATIC_FILES,ADD_JS_FILES,ADD_HEADER_SECTIONS"
      
