name: Vulture Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  vulture:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Vulture
        run: |
          python -m pip install --upgrade pip
          pip install vulture

      - name: Run Vulture
        run: |
          vulture . \
            --ignore-names "SECRET_KEY,DEBUG,ALLOWED_HOSTS,INSTALLED_APPS,MIDDLEWARE,ROOT_URLCONF,TEMPLATES,WSGI_APPLICATION,DATABASES,AUTH_PASSWORD_VALIDATORS,LANGUAGE_CODE,TIME_ZONE,USE_I18N,USE_TZ,STATIC_URL,DEFAULT_AUTO_FIELD,application,urlpatterns,name,slug,template_name,PANEL,PANEL_DASHBOARD,ADD_PANEL,ADD_INSTALLED_APPS,ADD_ANGULAR_MODULES,AUTO_DISCOVER_STATIC_FILES,ADD_JS_FILES,ADD_HEADER_SECTIONS,mock_approve,mock_roles,mock_templates,mock_user_details,mock_username,mock_users,mock_token,mock_get_token,mock_reverse,mock_image_data,mock_sec,mock_get_context,mock_fav,mock_flavors,mock_networks,mock_get_network_name,mock_keypair_list,mock_wait_ip,mock_context,has_more_data,has_prev_data,idx,get_security_groups,AdminInstructionsPanel,ExamplePanel,InstructionsPanel,ScriptPanel,PANEL_GROUP,PANEL_GROUP_NAME,PANEL_GROUP_DASHBOARD" \
            --exclude "myplugin/content/admin/panel.py,myplugin/content/eduvmstore/panel.py,myplugin/content/tutorial/panel.py,myplugin/enabled/_32000_my_new_dashboard.py,myplugin/content/admin/tests/test_adminindex.py,myplugin/content/admin/tests/test_adminviews.py,myplugin/content/eduvmstore/tests/test_apptemplate.py,myplugin/content/eduvmstore/tests/test_index.py,myplugin/content/eduvmstore/tests/test_instances.py,myplugin/content/eduvmstore/tests/test_views.py,myplugin/content/eduvmstore/utils.py,myplugin/content/eduvmstore/view/apptemplate.py,myplugin/content/example/panel.py,myplugin/content/instructions/panel.py,myplugin/content/script/panel.py,myplugin/enabled/_31150_tutorial_group.py,myplugin/enabled/_31200_tutorial_panel.py,myplugin/enabled/_31210_instructions_panel.py,myplugin/enabled/_31220_script_panel.py,myplugin/enabled/_31230_example_panel.py,myplugin/enabled/_31240_admin_instructions_panel.py"