name: Vulture Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  vulture:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Vulture
        run: |
          python -m pip install --upgrade pip
          pip install vulture

      - name: Run Vulture
        run: |
          vulture . \
          --ignore-names "SECRET_KEY,DEBUG,ALLOWED_HOSTS,CORS_ALLOW_ALL_ORIGINS,model,instantiation_attributes,account_attributes,security_groups,script,validate_name,updated_at,created,serializer_class,perform_create,approve,reject,favorites,delete_by_app_template,default_auto_field,pk,deleted,soft_delete_app_template,update_role,get_role_by_id,soft_delete_user,KeystoneAuthenticationMiddleware" \
          --exclude "eduvmstorebackend/config/settings.py,eduvmstorebackend/eduvmstore/apps.py,myplugin/content/admin/tests/,myplugin/content/eduvmstore/tests/"